name: Docker

on:
    workflow_dispatch:
    pull_request:
        types: [opened, reopened, synchronize]
    push:

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:               
    GenetateDocker:
        runs-on: Ubuntu-20.04

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                          
            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                key: ${{ secrets.SSH_KEY }}
                port: ${{ secrets.SSH_PORT }}
                script: |
                    echo ${{ secrets.GITHUB_TOKEN }} | docker login https://docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
                    docker-compose pull
                    docker-compose up -d
