name: Docker

on:
    workflow_dispatch:
    pull_request:
        types: [opened, reopened, synchronize]
    push:

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:               
    GenetateDocker:
        runs-on: Ubuntu-20.04

        steps:
            - name: Build and push
              run: |
                cd ..
                echo ${{ secrets.GITHUB_TOKEN }} | docker login https://docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
                docker build . --tag docker.pkg.github.com/jacksonveroneze/stock-service/stock-service:1.0.1
                docker push docker.pkg.github.com/jacksonveroneze/stock-service/stock-service:1.0.1
                
